name: Release
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      tag: ${{ steps.version.outputs.version }}
      should_release: ${{ steps.version.outputs.hasNextVersion }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: thenativeweb/get-next-version@main
        id: version

      - name: Update package.json
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update version to ${{ steps.version.outputs.version }}'
          tagging_message: 'v${{ steps.version.outputs.version }}'
  release:
    permissions:
      contents: write
      packages: write
    needs: update-version
    if: needs.update-version.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Create release tarball
        run: tar -czvf release.tar.gz -C dist .
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'release.tar.gz'
          name: 'Release v${{ needs.update-version.outputs.tag }}'
          tag: 'v${{ needs.update-version.outputs.tag }}'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  package:
    runs-on: ubuntu-latest
    needs: update-version
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    if: needs.update-version.outputs.should_release == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
