name: Release
on:
  push:
    branches:
      - main
jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      tag: ${{ steps.version.outputs.version }}
      should_release: ${{ steps.version.outputs.hasNextVersion }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: thenativeweb/get-next-version@main
        id: version

      - name: Update package.json
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update version to ${{ steps.version.outputs.version }}'
          tagging_message: 'v${{ steps.version.outputs.version }}'
  release:
    permissions:
      contents: write
      packages: write
    needs: update-version
    if: needs.update-version.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Create release tarball
        run: tar -czvf release.tar.gz -C dist .
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'release.tar.gz'
          name: 'Release v${{ needs.update-version.outputs.tag }}'
          tag: 'v${{ needs.update-version.outputs.tag }}'
