name: Update Version
on:
  push:
    branches:
      - main
jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        id: version
        uses: get-next-version@v1

      - name: Update package.json
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update version to ${{ steps.version.outputs.version }}'
          tagging_message: 'v${{ steps.version.outputs.version }}'
